#! /usr/bin/env python3

"""
-----------------------------------------------------------------------------------------------
File       : pgen
Author     : Neo.H
Date       : Oct 12, 2018
Type       : executable file
Description: A project gen tool named as pgen.
-----------------------------------------------------------------------------------------------
Options:
	-co <treename>: the tree name need to check out from cvs
	-help         : to display the help information
	-t  <tag>     : an optional option, if this option not specified, then to checkout the latest
version of target project.
-----------------------------------------------------------------------------------------------
Exit SIGs:
	0: normal exit
	1: fatal program error
	2: user input error
-----------------------------------------------------------------------------------------------
"""

from options import options;
import sys;

debug = True;

opt = options();

opt.set_support('co','\n\tthe tree name need to check out from cvs','treename');
opt.set_support('t','\n\tan optional option, if this option not specified, then to checkout the latest version of target project.','tag');
opt.set_support('help','\n\tto display the help information');

opt.load(sys.argv);

tree = opt.get_param('co');
tag  = opt.get_param('t'); ## if tag entered by user, then to use the first tag option entered by user.

if tree == False:
	## if tree name not entered by user, then need to print help information
	## this is the same action as call -help option.

## }

if tag == False:
	## if tag not entered by user, then need to check with latest project.

## }



## == after calling cvs co, then need to check if the project has successfully checked out.

sys.exit(0); ## normal exit
